# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
project_name: router
before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod tidy
builds:
  - env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X util.version={{ .Version }} -X util.commit={{ .Branch }}@{{ .Commit }} -X util.date={{ .Date }} -X util.builtBy=CI'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm
    binary: '{{ .ProjectName }}'
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      # if you are using this is a GitHub action or some other automated pipeline, you
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
dockers:
  - image_templates: ["habakke/router:{{ .Version }}-amd64"]
    ids: [router]
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    use_buildx: true
    extra_files:
      - conf/app.toml
      - conf/log.xml
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/habakke/router
      - --label=org.opencontainers.image.source=https://github.com/habakke/router
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses="Apache 2.0"
  - image_templates: ["habakke/router:{{ .Version }}-arm64v8"]
    binaries: [router]
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    use_buildx: true
    extra_files:
      - conf/app.toml
      - conf/log.xml
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/habakke/router
      - --label=org.opencontainers.image.source=https://github.com/habakke/router
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses="Apache 2.0"
  - image_templates: ["habakke/router:{{ .Version }}-386"]
    binaries: [router]
    goos: linux
    goarch: '386'
    dockerfile: Dockerfile
    use_buildx: true
    extra_files:
      - conf/app.toml
      - conf/log.xml
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/habakke/router
      - --label=org.opencontainers.image.source=https://github.com/habakke/router
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses="Apache 2.0"
docker_manifests:
  - name_template: habakke/router:{{ .Version }}
    image_templates:
      - habakke/router:{{ .Version }}-amd64
      - habakke/router:{{ .Version }}-arm64v8
      - habakke/router:{{ .Version }}-386
release:
# If you want to manually examine the release before its live, uncomment this line:
# draft: true
changelog:
  skip: true
